### PR TITLE
Updates to managing courses and profile setup test journeys

### PR DESCRIPTION
**Pull request by michalpiatek**

### CODE REVIEW

**Comment by willh** [comment]
Do not merge currently, WIP for review only

**Comment by willh** [comment]
Intended for merging now. Profile signup journey is working for single users, multi user parameterisation is not yet complete so will need to be set to 0 in percentage weightings in the load test runs, but the rest of the updates are worth having now.

**Review by m24murray — COMMENTED** [review]
Looks good so far. Could you update the readme to include some references to the new user's dataset, updates for the MySQL connection, how the truncating of the csrs tables works.

**Review by m24murray — COMMENTED** [review]
Ran a perf test to verify and all working as expected.

**Review by m24murray — DISMISSED** [review]
LGTM

**Review by m24murray — APPROVED** [review]
LGTM

**Pull request merged**
